# Generated by Django 2.2.4 on 2019-09-12 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_drawn_by(apps, schema_editor):
    Card = apps.get_model("games", "Card")
    for card in Card.objects.all():
        game = card.game
        j = card.index % game.players.count()
        ordered_players = [gp.user for gp in game.gameplayer_set.order_by("position")]
        card.drawn_by = ordered_players[j]
        card.save()


class Migration(migrations.Migration):

    dependencies = [("games", "0008_game_dnf")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="drawn_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_cards",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_drawn_by),
        migrations.AlterField(
            model_name="card",
            name="drawn_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
