# Generated by Django 2.2.4 on 2019-09-12 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_drawn_by_2(apps, schema_editor):
    Card = apps.get_model("games", "Card")
    for card in Card.objects.all():
        game = card.game
        j = card.index % game.players.count()
        ordered_gameplayers = game.gameplayer_set.order_by("position")
        card.drawn_by_2 = ordered_gameplayers[j]
        card.save()


class Migration(migrations.Migration):

    dependencies = [("games", "0009_card_drawn_by")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="drawn_by_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_cards_2",
                to="games.GamePlayer",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_drawn_by_2),
        migrations.AlterField(
            model_name="card",
            name="drawn_by_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_cards",
                to="games.GamePlayer",
            ),
        ),
    ]
